/// database_manager.dart
/// ======================
/// Data Access Object (DAO) for the ObjectBox embedded vector database.
///
/// Responsibilities
/// ----------------
/// 1. Lifecycle management — open / close the ObjectBox [Store].
/// 2. CRUD helpers — put assets, embeddings, and transcript segments.
/// 3. Hybrid KNN search — combine HNSW nearest-neighbour vector search with
///    standard metadata filter predicates (e.g. `mediaType != audio`).
///
/// Threading model
/// ---------------
/// [init] must be awaited before any other method is called.  All public
/// methods are synchronous once the store is open; ObjectBox's C++ runtime
/// handles its own internal locking.  For UI-thread safety, wrap heavy batch
/// operations (e.g. bulk inserts during indexing) in a [compute()] call or a
/// dedicated [Isolate].
///
/// Usage
/// -----
/// ```dart
/// final db = DatabaseManager();
/// await db.init();
///
/// // Store a new video asset
/// final assetId = await db.putAsset(MediaAsset(
///   filePath: '/storage/emulated/0/DCIM/clip.mp4',
///   mediaType: 1,
///   durationMs: 120000,
///   dateAddedMs: DateTime.now().millisecondsSinceEpoch,
/// ));
///
/// // Store an embedding linked to that asset
/// await db.putEmbedding(
///   FrameEmbedding(timestampMs: 3500, visualVector: myVector)
///     ..mediaAsset.targetId = assetId,
/// );
///
/// // Semantic search — returns closest frames, excluding audio files
/// final hits = db.searchVisualSemantic(queryVector, maxResults: 20);
/// ```
library;

import 'dart:async';
import 'dart:typed_data';

import 'package:objectbox/objectbox.dart';
import 'objectbox.g.dart'; // generated by build_runner — run Task 2.3 first
import 'models/media_asset.dart';
import 'models/frame_embedding.dart';
import 'models/transcript_segment.dart';

export 'models/media_asset.dart';
export 'models/frame_embedding.dart';
export 'models/transcript_segment.dart';

/// Singleton-style DAO wrapping the ObjectBox [Store].
///
/// **Production**: Create via the default constructor and call [init].
/// **Testing**: Use [DatabaseManager.fromStore] to inject a pre-opened [Store].
///
/// Call [dispose] when shutting down to release native resources.
class DatabaseManager {
  late final Store _store;
  Store get store => _store;

  late final Box<MediaAsset> _mediaBox;
  late final Box<FrameEmbedding> _embeddingBox;
  late final Box<TranscriptSegment> _transcriptBox;

  // ── Lifecycle ────────────────────────────────────────────────────────────────

  DatabaseManager();

  /// Test-only factory — injects an already-opened [Store].
  ///
  /// Use this in unit tests to share the [Store] lifecycle with the test
  /// fixture instead of calling [init] (which calls [openStore] internally):
  ///
  /// ```dart
  /// final store = Store(getObjectBoxModel(), directory: tmpDir.path);
  /// final db = DatabaseManager.fromStore(store);
  /// ```
  DatabaseManager.fromStore(Store store) {
    _store = store;
    _mediaBox = _store.box<MediaAsset>();
    _embeddingBox = _store.box<FrameEmbedding>();
    _transcriptBox = _store.box<TranscriptSegment>();
  }

  /// Opens the ObjectBox store at the default application data directory.
  ///
  /// On Android this resolves to `getFilesDir()/objectbox`.
  /// On Windows this resolves to `%LOCALAPPDATA%/<app>/objectbox`.
  ///
  /// Pass a custom [directory] for testing (e.g. a temp path) or to override
  /// the default location.
  Future<void> init({String? directory}) async {
    _store = await openStore(directory: directory);
    _mediaBox = _store.box<MediaAsset>();
    _embeddingBox = _store.box<FrameEmbedding>();
    _transcriptBox = _store.box<TranscriptSegment>();
  }

  /// Opens the ObjectBox store from an existing reference (for isolates).
  void initFromReference(ByteData reference) {
    _store = Store.fromReference(getObjectBoxModel(), reference);
    _mediaBox = _store.box<MediaAsset>();
    _embeddingBox = _store.box<FrameEmbedding>();
    _transcriptBox = _store.box<TranscriptSegment>();
  }

  /// Closes the ObjectBox store and releases all native resources.
  ///
  /// Must be called when the application is shutting down or when the
  /// database is no longer needed to avoid file-lock issues.
  void dispose() {
    if (!_store.isClosed()) {
      _store.close();
    }
  }

  // ── CRUD helpers ─────────────────────────────────────────────────────────────

  /// Insert or update a [MediaAsset] and return its database ID.
  ///
  /// If [asset.id] is 0 (default), ObjectBox assigns a new auto-increment ID.
  /// If [asset.id] is non-zero, the existing row is updated (upsert semantics).
  int putAsset(MediaAsset asset) {
    final id = _mediaBox.put(asset);
    _notifyAssetStream();
    return id;
  }

  /// Insert or update a [FrameEmbedding] and return its database ID.
  ///
  /// Ensure [embedding.mediaAsset] is set before calling:
  /// ```dart
  /// embedding.mediaAsset.target = existingAsset;
  /// // or:
  /// embedding.mediaAsset.targetId = knownAssetId;
  /// ```
  int putEmbedding(FrameEmbedding embedding) => _embeddingBox.put(embedding);

  /// Bulk-insert a list of [FrameEmbedding] objects in a single transaction.
  ///
  /// Significantly faster than calling [putEmbedding] in a loop for large
  /// batches (e.g. all keyframes from a single video file).
  List<int> putEmbeddings(List<FrameEmbedding> embeddings) =>
      _embeddingBox.putMany(embeddings);

  /// Insert or update a [TranscriptSegment] and return its database ID.
  int putTranscript(TranscriptSegment segment) => _transcriptBox.put(segment);

  /// Bulk-insert a list of [TranscriptSegment] objects in a single transaction.
  List<int> putTranscripts(List<TranscriptSegment> segments) =>
      _transcriptBox.putMany(segments);

  // ── Read helpers ─────────────────────────────────────────────────────────────

  /// Returns the [MediaAsset] with the given [id], or `null` if not found.
  MediaAsset? getAsset(int id) => _mediaBox.get(id);

  /// Returns an existing [MediaAsset] whose [filePath] exactly matches [path],
  /// or `null` if this file has not been indexed yet.
  ///
  /// Use this for deduplication before inserting: if this returns non-null and
  /// [MediaAsset.isFullyIndexed] is `true`, the file can be safely skipped.
  MediaAsset? findAssetByPath(String path) {
    final query = _mediaBox
        .query(MediaAsset_.filePath.equals(path))
        .build();
    try {
      return query.findFirst();
    } finally {
      query.close();
    }
  }

  /// Returns all [MediaAsset] rows not yet fully indexed.
  ///
  /// Used by the background indexing service on startup to resume interrupted
  /// jobs.
  List<MediaAsset> getPendingAssets() =>
      _mediaBox.query(MediaAsset_.isFullyIndexed.equals(false)).build().find();

  /// Returns all [TranscriptSegment] rows belonging to [assetId].
  List<TranscriptSegment> getTranscriptsForAsset(int assetId) {
    final query = _transcriptBox
        .query(TranscriptSegment_.mediaAsset.equals(assetId))
        .build();
    final results = query.find();
    query.close();
    return results;
  }

  // ── Streams ──────────────────────────────────────────────────────────────────
  final StreamController<List<MediaAsset>> _assetStreamController = StreamController.broadcast();

  /// Returns a reactive stream of all [MediaAsset]s, ordered by newest first.
  /// Used by the UI Provider to automatically rebuild the gallery on indexing updates.
  Stream<List<MediaAsset>> watchAllAssets() {
    // Yield the initial fetch
    Future.microtask(() => _notifyAssetStream());
    return _assetStreamController.stream;
  }

  void _notifyAssetStream() {
    final query = _mediaBox.query()
        .order(MediaAsset_.dateAddedMs, flags: Order.descending)
        .build();
    try {
      _assetStreamController.add(query.find());
    } finally {
      query.close();
    }
  }

  // ── Hybrid KNN Search ────────────────────────────────────────────────────────

  /// Performs a hybrid semantic search combining:
  ///   1. **HNSW nearest-neighbour** over [FrameEmbedding.visualVector] — pure
  ///      C++ native execution, zero Dart allocation on the hot path.
  ///   2. **Metadata filter** — restricts results to frames whose parent
  ///      [MediaAsset.mediaType] does NOT equal [excludeMediaType].
  ///
  /// Parameters
  /// ----------
  /// [queryVector]
  ///   The 1152-dim SigLIP SO400M query embedding, produced by the INT8 ONNX
  ///   model from Phase 1.  Must have exactly 1152 elements.
  ///
  /// [maxResults]
  ///   Upper bound on the number of [FrameEmbedding] rows returned.  ObjectBox
  ///   passes this as the `ef` beam-width cap to the HNSW search routine.
  ///   Default is 10.
  ///
  /// [excludeMediaType]
  ///   Frames whose parent asset has this [MediaAsset.mediaType] value are
  ///   excluded from the result set.  Default is `2` (Audio), which is the
  ///   correct behaviour for a visual search: we never want audio-only frames.
  ///   Pass `-1` to disable filtering and search across all media types.
  ///
  /// Returns
  ///   A list of [FrameEmbedding] objects ordered by ascending cosine distance
  ///   (closest match first), with a maximum length of [maxResults].
  ///
  /// Example
  /// -------
  /// ```dart
  /// final queryVec = siglipModel.encode(userQuery); // 1152 floats
  /// final hits = db.searchVisualSemantic(queryVec, maxResults: 20);
  /// for (final hit in hits) {
  ///   final asset = hit.mediaAsset.target!;
  ///   print('${asset.filePath} @ ${hit.timestampMs}ms');
  /// }
  /// ```
  List<FrameEmbedding> searchVisualSemantic(
    List<double> queryVector, {
    int maxResults = 10,
    int excludeMediaType = 2, // 2 = Audio; skip for visual-only search
  }) {
    assert(
      queryVector.length == 1152,
      'SigLIP SO400M requires exactly 1152-dim vectors; '
      'got ${queryVector.length}.',
    );

    // Step 1 — build KNN vector search condition
    final knnCondition = FrameEmbedding_.visualVector
        .nearestNeighborsF32(queryVector, maxResults);

    // Step 2 — attach metadata filter via relation link
    final queryBuilder = _embeddingBox.query(knnCondition);

    if (excludeMediaType >= 0) {
      // link() pushes the condition into the native HNSW post-filter stage,
      // avoiding a full Dart-side scan of the result list.
      queryBuilder.link(
        FrameEmbedding_.mediaAsset,
        MediaAsset_.mediaType.notEquals(excludeMediaType),
      );
    }

    final query = queryBuilder.build();
    try {
      return query.find();
    } finally {
      query.close(); // always release native query resources
    }
  }

  /// Variant of [searchVisualSemantic] that also returns each result's
  /// distance score (lower = more similar for cosine distance).
  ///
  /// Useful for displaying a confidence percentage in the UI:
  ///   `confidence = (1 - score).clamp(0, 1)`
  List<ObjectWithScore<FrameEmbedding>> searchVisualSemanticWithScores(
    List<double> queryVector, {
    int maxResults = 10,
    int excludeMediaType = 2,
  }) {
    assert(queryVector.length == 1152);

    final knnCondition = FrameEmbedding_.visualVector
        .nearestNeighborsF32(queryVector, maxResults);

    final queryBuilder = _embeddingBox.query(knnCondition);

    if (excludeMediaType >= 0) {
      queryBuilder.link(
        FrameEmbedding_.mediaAsset,
        MediaAsset_.mediaType.notEquals(excludeMediaType),
      );
    }

    final query = queryBuilder.build();
    try {
      return query.findWithScores();
    } finally {
      query.close();
    }
  }

  // ── Delete helpers ───────────────────────────────────────────────────────────

  /// Removes a [MediaAsset] and returns `true` if a row was deleted.
  ///
  /// Note: ObjectBox does NOT cascade-delete related [FrameEmbedding] or
  /// [TranscriptSegment] rows automatically.  Call [deleteEmbeddingsForAsset]
  /// and [deleteTranscriptsForAsset] first to avoid orphaned rows.
  bool deleteAsset(int assetId) => _mediaBox.remove(assetId);

  /// Removes all [FrameEmbedding] rows linked to [assetId].
  int deleteEmbeddingsForAsset(int assetId) {
    final query = _embeddingBox
        .query(FrameEmbedding_.mediaAsset.equals(assetId))
        .build();
    final ids = query.findIds();
    query.close();
    return _embeddingBox.removeMany(ids);
  }

  /// Removes all [TranscriptSegment] rows linked to [assetId].
  int deleteTranscriptsForAsset(int assetId) {
    final query = _transcriptBox
        .query(TranscriptSegment_.mediaAsset.equals(assetId))
        .build();
    final ids = query.findIds();
    query.close();
    return _transcriptBox.removeMany(ids);
  }
}
