/// media_core_ffi
/// ==============
/// Public Dart API for the media_core_ffi Flutter Native Asset plugin.
///
/// This library exposes the [MediaCore] class, which wraps the native
/// [MediaCoreBindings] (auto-generated by ffigen from media_core.h) behind
/// a clean, memory-safe Dart interface.
///
/// Usage
/// -----
/// ```dart
/// import 'package:media_core_ffi/media_core_ffi.dart';
///
/// final result = MediaCore.extractAudio('/path/to/video.mp4');
/// if (result != null) {
///   // result is a Uint8List of int16 PCM samples, 16 kHz mono
///   processAudio(result);
/// }
/// ```
///
/// Memory management
/// -----------------
/// [MediaCore.extractAudio] handles calling [MediaCoreBindings.free_audio_buffer]
/// automatically — callers receive a safe Dart [Uint8List] copy and do not
/// need to manage any native heap memory.
///
/// Threading
/// ---------
/// The underlying C function [extract_audio_pcm] is blocking (synchronous
/// demux/decode/resample for the entire file). Always call [MediaCore.extractAudio]
/// from a Dart Isolate via [compute()] or [Isolate.spawn()] — never from the
/// UI thread or an async event handler.
library media_core_ffi;

import 'dart:ffi' as ffi;
import 'dart:io' show Platform;
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'src/media_core_bindings.dart';

export 'src/media_core_bindings.dart' show MediaCoreBindings, AudioBufferResult;

// ── Library loader ─────────────────────────────────────────────────────────────

/// Loads the [MediaCoreBindings] from the native shared library bundled by
/// Flutter's Native Assets build system.
///
/// On Windows  → media_core.dll
/// On Android  → libmedia_core.so
/// Other Linux → libmedia_core.so (e.g. for desktop Linux future support)
MediaCoreBindings _loadBindings() {
  const _libName = 'media_core';

  final lib = Platform.isWindows
      ? ffi.DynamicLibrary.open('$_libName.dll')
      : ffi.DynamicLibrary.open('lib$_libName.so');

  return MediaCoreBindings(lib);
}

/// Singleton [MediaCoreBindings] instance. Loaded lazily on first use.
final MediaCoreBindings _bindings = _loadBindings();

// ── Public API ─────────────────────────────────────────────────────────────────

/// High-level, memory-safe wrapper around the native [extract_audio_pcm] C function.
class MediaCore {
  const MediaCore._();

  /// Extract and VAD-filter the audio track from [videoPath].
  ///
  /// Returns a [Uint8List] whose bytes are the raw int16 PCM samples
  /// (16 kHz, mono, little-endian). The list length equals
  /// `sample_count * 2` bytes.
  ///
  /// Returns `null` if:
  ///   - The file does not exist or cannot be opened.
  ///   - No audio track is present.
  ///   - A codec error occurs.
  ///   - All decoded audio is classified as silence by the VAD gate.
  ///
  /// [threshold] overrides the default VAD RMS threshold (300 ≈ −40 dBFS).
  /// Pass a lower value to keep softer speech; pass a higher value to
  /// discard more background noise.
  ///
  /// **Threading**: This call blocks the calling isolate for the full duration
  /// of the demux/decode/resample pipeline. Always run it via [compute()].
  static Uint8List? extractAudio(String videoPath, {int threshold = 300}) {
    // Allocate native UTF-8 string for the path
    final pathPtr = videoPath.toNativeUtf8().cast<ffi.Char>();
    AudioBufferResult? result;
    try {
      result = _bindings.extract_audio_pcm(pathPtr);
    } finally {
      // Always free the path string — independent of whether extraction succeeded
      malloc.free(pathPtr);
    }

    if (result == null || result.sample_count <= 0 || result.data == ffi.nullptr) {
      return null;
    }

    try {
      // Copy int16 samples into a Dart-managed Uint8List (2 bytes per sample).
      final byteCount = result.sample_count * 2;
      final bytes = Uint8List(byteCount);
      final nativeBytes = result.data.cast<ffi.Uint8>();
      for (int i = 0; i < byteCount; i++) {
        bytes[i] = nativeBytes[i];
      }
      return bytes;
    } finally {
      // Release the native PCM buffer allocated by extract_audio_pcm()'s malloc()
      _bindings.free_audio_buffer(result.data);
    }
  }

  /// Compute the RMS energy of a [samples] buffer (int16 PCM).
  ///
  /// Useful for implementing a custom VAD gate or metering UI.
  /// Returns 0 if [samples] is empty.
  static int rms(ffi.Pointer<ffi.Int16> samples, int sampleCount) {
    return _bindings.vad_rms(samples, sampleCount);
  }

  /// Returns `true` if the RMS of [samples] exceeds [threshold].
  ///
  /// Mirrors the VAD gate applied internally by [extract_audio_pcm].
  static bool isSpeech(
    ffi.Pointer<ffi.Int16> samples,
    int sampleCount, {
    int threshold = 300,
  }) {
    return _bindings.vad_is_speech(samples, sampleCount, threshold) == 1;
  }
}
