// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/frame_embedding.dart';
import 'models/media_asset.dart';
import 'models/transcript_segment.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7713976757524249792),
    name: 'FrameEmbedding',
    lastPropertyId: const obx_int.IdUid(4, 6907992978872321294),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 473164157140023672),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7816330484751169744),
        name: 'mediaAssetId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6743310155909358403),
        relationField: 'mediaAsset',
        relationTarget: 'MediaAsset',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6922544754971818898),
        name: 'timestampMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6907992978872321294),
        name: 'visualVector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 8856058368327420223),
        hnswParams: obx_int.ModelHnswParams(dimensions: 1152, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5340478602833278925),
    name: 'MediaAsset',
    lastPropertyId: const obx_int.IdUid(6, 6442497113210470175),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3664323223145021442),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8731682940608261209),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1593783701497852872),
        name: 'mediaType',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(3, 218370182803903895),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6342015677041979024),
        name: 'durationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7957217701986121481),
        name: 'dateAddedMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6442497113210470175),
        name: 'isFullyIndexed',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7415864909168669068),
    name: 'TranscriptSegment',
    lastPropertyId: const obx_int.IdUid(6, 6154025501165331678),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3809849612212397907),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8106776348320291620),
        name: 'mediaAssetId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 8831971784047240680),
        relationField: 'mediaAsset',
        relationTarget: 'MediaAsset',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2490205079717110403),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5022394701016156308),
        name: 'startTimeMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5882041210826318611),
        name: 'endTimeMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6154025501165331678),
        name: 'sourceType',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(5, 2893421811419798264),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 7415864909168669068),
    lastIndexId: const obx_int.IdUid(5, 2893421811419798264),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FrameEmbedding: obx_int.EntityDefinition<FrameEmbedding>(
      model: _entities[0],
      toOneRelations: (FrameEmbedding object) => [object.mediaAsset],
      toManyRelations: (FrameEmbedding object) => {},
      getId: (FrameEmbedding object) => object.id,
      setId: (FrameEmbedding object, int id) {
        object.id = id;
      },
      objectToFB: (FrameEmbedding object, fb.Builder fbb) {
        final visualVectorOffset = fbb.writeListFloat32(object.visualVector);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.mediaAsset.targetId);
        fbb.addInt64(2, object.timestampMs);
        fbb.addOffset(3, visualVectorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final timestampMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final visualVectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = FrameEmbedding(
          timestampMs: timestampMsParam,
          visualVector: visualVectorParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.mediaAsset.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.mediaAsset.attach(store);
        return object;
      },
    ),
    MediaAsset: obx_int.EntityDefinition<MediaAsset>(
      model: _entities[1],
      toOneRelations: (MediaAsset object) => [],
      toManyRelations: (MediaAsset object) => {},
      getId: (MediaAsset object) => object.id,
      setId: (MediaAsset object, int id) {
        object.id = id;
      },
      objectToFB: (MediaAsset object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, filePathOffset);
        fbb.addInt64(2, object.mediaType);
        fbb.addInt64(3, object.durationMs);
        fbb.addInt64(4, object.dateAddedMs);
        fbb.addBool(5, object.isFullyIndexed);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final mediaTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final durationMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final dateAddedMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final isFullyIndexedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = MediaAsset(
          filePath: filePathParam,
          mediaType: mediaTypeParam,
          durationMs: durationMsParam,
          dateAddedMs: dateAddedMsParam,
          isFullyIndexed: isFullyIndexedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    TranscriptSegment: obx_int.EntityDefinition<TranscriptSegment>(
      model: _entities[2],
      toOneRelations: (TranscriptSegment object) => [object.mediaAsset],
      toManyRelations: (TranscriptSegment object) => {},
      getId: (TranscriptSegment object) => object.id,
      setId: (TranscriptSegment object, int id) {
        object.id = id;
      },
      objectToFB: (TranscriptSegment object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.mediaAsset.targetId);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.startTimeMs);
        fbb.addInt64(4, object.endTimeMs);
        fbb.addInt64(5, object.sourceType);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startTimeMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final endTimeMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final sourceTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = TranscriptSegment(
          text: textParam,
          startTimeMs: startTimeMsParam,
          endTimeMs: endTimeMsParam,
          sourceType: sourceTypeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.mediaAsset.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.mediaAsset.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FrameEmbedding] entity fields to define ObjectBox queries.
class FrameEmbedding_ {
  /// See [FrameEmbedding.id].
  static final id = obx.QueryIntegerProperty<FrameEmbedding>(
    _entities[0].properties[0],
  );

  /// See [FrameEmbedding.mediaAsset].
  static final mediaAsset = obx.QueryRelationToOne<FrameEmbedding, MediaAsset>(
    _entities[0].properties[1],
  );

  /// See [FrameEmbedding.timestampMs].
  static final timestampMs = obx.QueryIntegerProperty<FrameEmbedding>(
    _entities[0].properties[2],
  );

  /// See [FrameEmbedding.visualVector].
  static final visualVector = obx.QueryHnswProperty<FrameEmbedding>(
    _entities[0].properties[3],
  );
}

/// [MediaAsset] entity fields to define ObjectBox queries.
class MediaAsset_ {
  /// See [MediaAsset.id].
  static final id = obx.QueryIntegerProperty<MediaAsset>(
    _entities[1].properties[0],
  );

  /// See [MediaAsset.filePath].
  static final filePath = obx.QueryStringProperty<MediaAsset>(
    _entities[1].properties[1],
  );

  /// See [MediaAsset.mediaType].
  static final mediaType = obx.QueryIntegerProperty<MediaAsset>(
    _entities[1].properties[2],
  );

  /// See [MediaAsset.durationMs].
  static final durationMs = obx.QueryIntegerProperty<MediaAsset>(
    _entities[1].properties[3],
  );

  /// See [MediaAsset.dateAddedMs].
  static final dateAddedMs = obx.QueryIntegerProperty<MediaAsset>(
    _entities[1].properties[4],
  );

  /// See [MediaAsset.isFullyIndexed].
  static final isFullyIndexed = obx.QueryBooleanProperty<MediaAsset>(
    _entities[1].properties[5],
  );
}

/// [TranscriptSegment] entity fields to define ObjectBox queries.
class TranscriptSegment_ {
  /// See [TranscriptSegment.id].
  static final id = obx.QueryIntegerProperty<TranscriptSegment>(
    _entities[2].properties[0],
  );

  /// See [TranscriptSegment.mediaAsset].
  static final mediaAsset =
      obx.QueryRelationToOne<TranscriptSegment, MediaAsset>(
        _entities[2].properties[1],
      );

  /// See [TranscriptSegment.text].
  static final text = obx.QueryStringProperty<TranscriptSegment>(
    _entities[2].properties[2],
  );

  /// See [TranscriptSegment.startTimeMs].
  static final startTimeMs = obx.QueryIntegerProperty<TranscriptSegment>(
    _entities[2].properties[3],
  );

  /// See [TranscriptSegment.endTimeMs].
  static final endTimeMs = obx.QueryIntegerProperty<TranscriptSegment>(
    _entities[2].properties[4],
  );

  /// See [TranscriptSegment.sourceType].
  static final sourceType = obx.QueryIntegerProperty<TranscriptSegment>(
    _entities[2].properties[5],
  );
}
