import os
from pathlib import Path
from pydantic_settings import BaseSettings

# Absolute path to the project root (the folder that contains app/, models/, etc.)
# Works regardless of which directory the server is started from.
_PROJECT_ROOT = Path(__file__).resolve().parents[2]


class Settings(BaseSettings):
    PROJECT_NAME: str = "Semantic Video Search"
    API_V1_STR: str = "/api/v1"

    # ── Qdrant connection ──────────────────────────────────────────────────
    # QDRANT_USE_SERVER=false (default) → local embedded DB, no Docker needed.
    # QDRANT_USE_SERVER=true            → HTTP to QDRANT_HOST:QDRANT_PORT.
    QDRANT_USE_SERVER: bool = False
    QDRANT_HOST: str = os.getenv("QDRANT_HOST", "localhost")
    QDRANT_PORT: int = int(os.getenv("QDRANT_PORT", 6333))
    QDRANT_COLLECTION: str = os.getenv("QDRANT_COLLECTION", "video_embeddings")

    # Local embedded DB path (used when QDRANT_USE_SERVER=false)
    QDRANT_LOCAL_PATH: str = str(_PROJECT_ROOT / "qdrant_local_db")

    # ══════════════════════════════════════════════════════════════════════
    # SigLIP Model Tier Selection (Phase 1 — Dual-Model Support)
    # ══════════════════════════════════════════════════════════════════════
    #
    # Two quality tiers are supported. Switch via .env or environment var:
    #
    #   SIGLIP_TIER=base  (default)
    #     Model : google/siglip-base-patch16-224
    #     Size  : ~26 MB per encoder (split mode)
    #     Dims  : 768-dim embeddings
    #     Speed : Faster inference; suitable for real-time frame indexing
    #     Use when: RAM is tight or throughput matters more than quality
    #
    #   SIGLIP_TIER=hq
    #     Model : google/siglip-so400m-patch14-224  (SO400M variant)
    #     Size  : ≤ 300 MB (vision encoder, INT8)
    #     Dims  : 768-dim embeddings (same space, richer feature extraction)
    #     Speed : Slower; recommended for nightly/background indexing jobs
    #     Use when: highest semantic search quality is the priority
    #
    # To switch:  Set SIGLIP_TIER=hq in your .env file.
    # Both tiers share the same Qdrant collection schema (768-dim vectors).
    # You must re-index all media after switching tiers (embeddings differ).
    # ──────────────────────────────────────────────────────────────────────
    SIGLIP_TIER: str = "base"   # "base" | "hq"

    # ── Model identity (resolved from SIGLIP_TIER at startup) ─────────────
    # HuggingFace model ID used for the processor (tokenizer + image processor).
    # The weights themselves come from the local ONNX file below.
    # Override individually via .env if you need a non-standard model path.
    @property
    def MODEL_NAME(self) -> str:
        """HuggingFace model ID matching the active SigLIP tier."""
        _tier_map = {
            "base": "google/siglip-base-patch16-224",
            "hq":   "google/siglip-so400m-patch14-224",
        }
        tier = self.SIGLIP_TIER.lower()
        if tier not in _tier_map:
            raise ValueError(
                f"Unknown SIGLIP_TIER='{tier}'. Valid options: base, hq"
            )
        return _tier_map[tier]

    # ── ONNX model paths ──────────────────────────────────────────────────
    # Resolved to absolute paths so the app works from any working directory.
    #
    # Base tier models (prototype-proven, always available after running
    # tools/export_split_models.py):
    ONNX_MODEL_DIR: str = str(_PROJECT_ROOT / "models" / "siglip_int8")
    ONNX_MODEL_FILE: str = "model_quantized.onnx"   # combined FP32 fallback

    # Split encoder filenames (base tier — generated by export_split_models.py)
    ONNX_VISION_MODEL_FILE: str = "vision_encoder_int8.onnx"
    ONNX_TEXT_MODEL_FILE:   str = "text_encoder_int8.onnx"

    # ── High-Quality (HQ) SO400M model paths ──────────────────────────────
    # Generated by: python tools/quantize_siglip.py --tier hq
    # Output:       assets/models/siglip_vision_int8.onnx  (vision only)
    # Text encoder: re-export with export_split_models.py pointing to SO400M
    #               or use the base text encoder (embeddings are NOT compatible
    #               across tiers — you must use matching vision+text encoders).
    HQ_MODEL_DIR: str = str(_PROJECT_ROOT / "assets" / "models")
    HQ_VISION_MODEL_FILE: str = "siglip_vision_int8.onnx"

    @property
    def ACTIVE_ONNX_DIR(self) -> str:
        """Resolve the ONNX model directory for the active SigLIP tier."""
        return self.HQ_MODEL_DIR if self.SIGLIP_TIER.lower() == "hq" else self.ONNX_MODEL_DIR

    @property
    def ACTIVE_VISION_FILE(self) -> str:
        """Resolve the vision encoder filename for the active SigLIP tier."""
        return self.HQ_VISION_MODEL_FILE if self.SIGLIP_TIER.lower() == "hq" else self.ONNX_VISION_MODEL_FILE

    # ── Model mode selector ───────────────────────────────────────────────
    # Controls whether the engine uses separate vision + text encoder sessions
    # or the single combined model_quantized.onnx.
    #
    #   None  (default) → AUTO: use split models if both files exist on disk,
    #                     otherwise silently fall back to the combined model.
    #   True            → FORCE SPLIT: raise FileNotFoundError at startup if
    #                     either split file is missing (useful in CI / prod).
    #   False           → FORCE COMBINED: always use model_quantized.onnx,
    #                     even if split files are present on disk.
    #
    # Set via .env:  USE_SPLIT_MODELS=true / false / (omit for auto)
    USE_SPLIT_MODELS: bool | None = True

    # ── ONNX Runtime performance flags ───────────────────────────────────
    # Number of threads for intra-op parallelism (0 = ORT auto-detect).
    # On mobile / mid-range CPUs, 2-4 is usually optimal.  Keep 0 for auto.
    ORT_INTRA_OP_THREADS: int = 0
    # Number of threads for inter-op parallelism (0 = ORT auto-detect).
    ORT_INTER_OP_THREADS: int = 0
    # Enable ORT memory arena (reduces allocator overhead on repeated calls).
    ORT_ENABLE_MEMORY_ARENA: bool = True

    # ── Inference batching ────────────────────────────────────────────────
    # Frames per inference batch.  Lower = less RAM, higher = more throughput.
    # 8 is a good default for mid-range CPUs; increase if RAM allows.
    INFERENCE_BATCH_SIZE: int = 8

    # ── Frame / scene detection ───────────────────────────────────────────
    # FFmpeg scene-change score threshold (0.0 – 1.0 scale).
    # 0.3 is a good default: catches real cuts, ignores minor lighting shifts.
    # Lower = more frames extracted (more sensitive).
    FFMPEG_SCENE_SCORE: float = 0.3
    # FPS used for uniform-sampling fallback when scene detection produces 0 frames.
    FALLBACK_FPS: float = 1.0
    # LEGACY: kept for backward-compat; no longer used by pipeline.py.
    SCENE_THRESHOLD: float = 27.0

    # ══════════════════════════════════════════════════════════════════════
    # Phase 1 — PP-OCR Model Paths (Text Extraction Track)
    # ══════════════════════════════════════════════════════════════════════
    # Generated by: python tools/quantize_ocr.py
    # Both models must exist for OCR features to be available.
    #
    # PPOCR_MODEL_DIR defaults to assets/models/ (shared with SigLIP HQ
    # and Whisper assets — all production models live under assets/).
    PPOCR_MODEL_DIR: str = str(_PROJECT_ROOT / "assets" / "models")
    PPOCR_DET_MODEL_FILE: str = "ppocr_det_int8.onnx"   # DBNet text detector
    PPOCR_REC_MODEL_FILE: str = "ppocr_rec_int8.onnx"   # CRNN text recogniser

    @property
    def PPOCR_DET_PATH(self) -> str:
        """Absolute path to the PP-OCR detection ONNX model."""
        return os.path.join(self.PPOCR_MODEL_DIR, self.PPOCR_DET_MODEL_FILE)

    @property
    def PPOCR_REC_PATH(self) -> str:
        """Absolute path to the PP-OCR recognition ONNX model."""
        return os.path.join(self.PPOCR_MODEL_DIR, self.PPOCR_REC_MODEL_FILE)

    @property
    def PPOCR_AVAILABLE(self) -> bool:
        """True if both PP-OCR models exist on disk (OCR features enabled)."""
        return os.path.exists(self.PPOCR_DET_PATH) and os.path.exists(self.PPOCR_REC_PATH)

    # ══════════════════════════════════════════════════════════════════════
    # Phase 1 — Whisper Tiny Model Paths (Audio / Transcription Track)
    # ══════════════════════════════════════════════════════════════════════
    # Generated by: python tools/export_whisper.py
    # The Optimum exporter produces a multi-file bundle — all three ONNX
    # files must be present for transcription to function.
    WHISPER_MODEL_DIR: str = str(_PROJECT_ROOT / "assets" / "models" / "whisper_tiny_int8")

    @property
    def WHISPER_ENCODER_PATH(self) -> str:
        """Path to Whisper encoder ONNX (mel spectrogram → hidden states)."""
        return os.path.join(self.WHISPER_MODEL_DIR, "encoder_model.onnx")

    @property
    def WHISPER_DECODER_PATH(self) -> str:
        """Path to Whisper decoder ONNX (initial token generation pass)."""
        return os.path.join(self.WHISPER_MODEL_DIR, "decoder_model.onnx")

    @property
    def WHISPER_DECODER_PAST_PATH(self) -> str:
        """Path to Whisper decoder-with-past ONNX (incremental decoding)."""
        return os.path.join(self.WHISPER_MODEL_DIR, "decoder_with_past_model.onnx")

    @property
    def WHISPER_AVAILABLE(self) -> bool:
        """True if all three Whisper ONNX files exist (transcription enabled)."""
        return all(
            os.path.exists(p) for p in [
                self.WHISPER_ENCODER_PATH,
                self.WHISPER_DECODER_PATH,
                self.WHISPER_DECODER_PAST_PATH,
            ]
        )

    # ══════════════════════════════════════════════════════════════════════
    # Phase 1 — Native C Library (media_core_ffi)
    # ══════════════════════════════════════════════════════════════════════
    # The Flutter Native Assets build system compiles media_core.c and
    # bundles the resulting .dll/.so automatically during `flutter build`.
    # This path is used ONLY by the Python-side verification runner
    # (tools/verify_phase1.py) and any Python integration tests.
    # Flutter/Dart loads the library via dart:ffi NativeAssets — no path
    # configuration needed on the Flutter side.
    NATIVE_LIB_DIR: str = str(_PROJECT_ROOT / "assets" / "native")

    @property
    def NATIVE_LIB_PATH(self) -> str:
        """
        Platform-resolved path to the compiled media_core shared library.
        Used by tools/verify_phase1.py for smoke testing only.
        Flutter loads the library automatically via Native Assets.
        """
        import platform
        system = platform.system()
        if system == "Windows":
            return os.path.join(self.NATIVE_LIB_DIR, "windows", "x64", "media_core.dll")
        elif system == "Linux":
            return os.path.join(self.NATIVE_LIB_DIR, "android", "arm64", "libmedia_core.so")
        else:
            return os.path.join(self.NATIVE_LIB_DIR, "libmedia_core.so")

    # ── Legacy CUDA flag (kept for compatibility; ONNX always runs on CPU) ─
    USE_CUDA: bool = True

    @property
    def DEVICE(self) -> str:
        """Always returns 'cpu' – ONNX Runtime handles its own execution providers."""
        return "cpu"

    class Config:
        env_file = ".env"
        extra = "ignore"


settings = Settings()
